import test from "node:test";
import assert from "node:assert/strict";
import {scoreOpportunity} from "../lib/fit";
import type {CompanyTarget} from "../lib/targets";

const target=(country="United Kingdom"):CompanyTarget=>({company:"Test Fab",tier:"A",country,region:country==="United States"?"North America":"UK & Ireland",careers:"https://example.com/careers",focus:"Semiconductor process"});

test("graduate process role scores as likely",()=>{const op=scoreOpportunity(target(),"Graduate Process Engineer","Physics degree. MATLAB, cleanroom and photolithography.","https://example.com/job/1");assert.equal(op.eligibility,"likely");assert.ok(op.fitScore>=70)});
test("senior role with experience requirement is rejected",()=>{const op=scoreOpportunity(target(),"Senior Process Engineer","Minimum 7 years experience required.","https://example.com/job/2");assert.equal(op.eligibility,"unlikely")});
test("sponsorship restriction requires Ata review",()=>{const op=scoreOpportunity(target(),"Graduate Technician","We are unable to offer visa sponsorship.","https://example.com/job/3");assert.equal(op.eligibility,"manual-check")});
test("senior wording in description does not reject junior title",()=>{const op=scoreOpportunity(target(),"Equipment Technician","Reports to the Senior Manager. We will not be able to offer Visa sponsorship.","https://example.com/job/4");assert.equal(op.eligibility,"manual-check");assert.ok(!op.concerns.includes("Senior-level title"))});
test("non-US foreign role keeps its fit score but flags visa review",()=>{const op=scoreOpportunity(target("France"),"Process Engineer","Physics, process and cleanroom experience.","https://example.com/job/5");assert.equal(op.eligibility,"manual-check");assert.ok(op.fitScore>=50);assert.ok(op.concerns.some(x=>x.includes("France")))});
test("United States roles are always eliminated",()=>{const op=scoreOpportunity(target("United States"),"Graduate Process Engineer","Physics, process and cleanroom experience.","https://example.com/job/us");assert.equal(op.eligibility,"unlikely");assert.equal(op.fitScore,0)});
test("requirements above one year are eliminated",()=>{for(const requirement of ["2+ years of experience required","At least 2 years relevant experience","Experience: 2-3 years","0~3 years of experience","Minimum two years of industry experience"]){const op=scoreOpportunity(target(),"Process Engineer",`Physics and cleanroom. ${requirement}.`,"https://example.com/job/experience");assert.equal(op.eligibility,"unlikely",requirement);assert.ok(op.concerns.includes("More than 1 year of experience requested"),requirement)}});
test("zero to one year requirements remain eligible",()=>{for(const requirement of ["0-1 years of experience","One year of experience preferred"]){const op=scoreOpportunity(target(),"Graduate Process Engineer",`Physics, process and cleanroom. ${requirement}.`,"https://example.com/job/entry");assert.notEqual(op.eligibility,"unlikely",requirement)}});
test("new Termotes cleanroom systems experience contributes to fit",()=>{const op=scoreOpportunity(target(),"Graduate Cleanroom Facilities Engineer","Support HVAC, filtration, air-handling, humidity control, P&IDs and URS for cleanroom facilities.","https://example.com/job/facilities");assert.ok(op.fitReasons.includes("Cleanroom facilities and systems fit"));assert.ok(op.fitScore>=70)});
test("lead and significant experience roles are rejected",()=>{const lead=scoreOpportunity(target(),"Lead Validation Engineer","Physics and test development.","https://example.com/job/6");const experienced=scoreOpportunity(target(),"Equipment Engineer","Significant experience within semiconductor manufacturing is essential.","https://example.com/job/7");assert.equal(lead.eligibility,"unlikely");assert.equal(experienced.eligibility,"unlikely")});
